const lyricsData = [
  { time: 22.514, text: "I don't want a friend (just me)" },
  { time: 26.101, text: "I want my life in two (my life in two)" },
  { time: 29.832, text: "Just one more night" },
  { time: 31.989, text: "Waiting to get there" },
  { time: 37.278, text: "Waiting for you (all night)" },
  { time: 40.077, text: "I'm done fighting all night (waiting for you)" },
  { time: 46.372, text: "When I'm around slow dancing in the dark" },
  { time: 51.693, text: "Don't follow me, you'll end up in my arms" },
  { time: 55.629, text: "You have made up your mind" },
  { time: 58.814, text: "I don't need no more signs" },
  { time: 61.911, text: "Can you?" },
  { time: 64.013, text: "Can you?" },
  { time: 67.487, text: "Give me reasons we should be complete" },
  { time: 73.162, text: "You should be with him, I can't compete" },
  { time: 78.361, text: "You looked at me like I was someone else, oh well" },
  { time: 85.383, text: "Can't you see? (Can't you see?)" },
  { time: 90.974, text: "I don't wanna slow dance (I don't want to slow dance)" },
  { time: 95.518, text: "In the dark" },
  { time: 102.687, text: "Dark" },
  { time: 108.645, text: "When you gotta run" },
  { time: 111.885, text: "Just hear my voice in you (my voice in you)" },
  { time: 117.683, text: "Shutting me out of you (shutting me out of you)" },
  { time: 123.530, text: "Doing so great (so great, so great)" },
  { time: 127.475, text: "You" },
  { time: 131.208, text: "Used to be the one (used to be the one)" },
  { time: 133.960, text: "To hold you when you fall" },
  { time: 137.370, text: "Yeah, yeah, yeah (when you fall, when you fall)" },
  { time: 139.977, text: "I don't fuck with your tone (I don't fuck with your tone)" },
  { time: 142.394, text: "I don't wanna go home (I don't wanna go home)" },
  { time: 144.839, text: "Can it be one night?" },
  { time: 147.768, text: "Can you?" },
  { time: 150.706, text: "Can you?" },
  { time: 154.231, text: "Give me reasons we should be complete" },
  { time: 159.651, text: "You should be with him, I can't compete" },
  { time: 164.765, text: "You looked at me like I was someone else, oh well" },
  { time: 171.787, text: "Can't you see?" },
  { time: 177.529, text: "I don't wanna slow dance (I don't want to slow dance)" },
  { time: 182.756, text: "In the dark" },
  { time: 189.444, text: "Dark" },
  { time: 193.534, text: "In the dark" },
  { time: 200.160, text: "Dark" }
];